### ISSUE TITLE
Improve diff implementation

### ISSUE THREAD

**Issue by jzaefferer** [jquery/qunit#364]
Potential diff implementations:

* https://github.com/kpdecker/jsdiff
* https://github.com/cemerick/jsdifflib (Timo recommended this one, [using it by monkey-patching already](https://gerrit.wikimedia.org/r/#/c/86657/6/modules/ve/test/ve.qunit.js))

Related tickets: #335, #348, #478, #363, #483

**Comment by gauravmittal1995** [comment]
@jzaefferer @leobalter Hey, I want to work on this for GSoC 15. Can u help me get started??

**Comment by AnishChandran** [comment]
I would like to contribute ! Can someone get me started ?

**Comment by leobalter** [comment]
There some parts of the current diff tool that we would like to enhance. We can improve its code or use another external tool, if it doesn't bring more problems to deal with.

We can look at the following issues to see specific points to lead the way to improve it:

- [ ] #335: Show diff only when it helps
- [ ] #348: Confusing line breaks
- [ ] #478: Backslash in string inconsistency
- [ ] #363: Diff only leafs for (big) objects
- [ ] #483: QUnit.diff should be given dumped values before html escape

**Comment by AnishChandran** [comment]
I thought of starting with #335  It´s a great idea to use the length factor to determine whether the diff is valid or not ! Changing the head.js to check the length condition at first would help this ryt ?

**Comment by jzaefferer** [comment]
> It´s a great idea to use the length factor to determine whether the diff is valid or not !

As I wrote in #335, comparing the length isn't as easy as it seems.

> Changing the head.js to check the length condition at first would help this ryt ?

I'm not sure what `head.js` you're referring to.

Anyway, I think in this case it would be good to start with a few diff test cases that show the potential for improvements. A group of actual/expected values that currently end up with more or less useless diffs.

**Comment by asped08** [comment]
Gsoc 2015 - QUnit - Better diff output

I am interested in this and I am trying to understand the code any help would be great

**Comment by gauravmittal1995** [comment]
@leobalter @jzaefferer Hey, How does the following look?

![screenshot from 2015-03-05 16 57 46](https://cloud.githubusercontent.com/assets/6555434/6504090/5bc8f45c-c359-11e4-9034-bf7765f11173.png)

This is using google's diff-patch-match with some changes done by me. Currently its supported for strings, but we can add it for array objects as well.

**Comment by leobalter** [comment]
The diff should work not only for strings, but for dumped object representations. See our QUnit.dump to check how it shows arrays, functions, objects, etc.

I can't say how  good the diff looks from 2 strings only, it needs more information.

**Comment by leobalter** [comment]
@asped08, if you write a failing assertion, (like `assert.equal({ foo: "foo" }, { foo: "bar" })`) you can see the current diff in QUnit's  test report. From there, there are some fixes and improvements on the already addressed issues.

**Comment by AnishChandran** [comment]
I just thought that we could deal with #348  first since it seems to be little less complicated 
http://fiddle.jshell.net/sj6kdj9g/ 
Is this an simple example about confusing line breaks in diff ? since the "gre": "foo" should be aligned with "foo": "bar ? should we focus on qunit.js and qunit.css and change the way in which the diffs are displayed ?

**Comment by shivamdixit** [comment]
Just wanted to know that what are the issues in using `jsdifflib` directly? If we directly import it as a module.

**Comment by garan** [comment]
Just a heads-up.
I thought I would mention prettydiff here, to make sure you guys have considered it.

I have been using jsdifflib, as it looked to be the best option, months ago (not sure why I skipped prettydiff ..probably seemed like too much at the time).
However, I only use difflib.SequenceMatcher() and found jsdifflib code easy to adapt.

Prettydiff was originally developed from jsdifflib and has been developed quite a bit further.

The only feature of prettydiff that I'm interested in is character-diffs.
However, if you are displaying on the front-end, you might want to check it out.

Cheers.

P.S. These 'diff' modules really should keep their diff code separate, ideally in a separate module.  I'm tempted to fork..

**Comment by jzaefferer** [comment]
On the list above, only #363 is still open, and we have a WIP PR for that. I don't think we need this meta ticket anymore.

**Comment by Mr21** [comment]
@garan, I recently finish a diff implementation here: https://github.com/Mr21/diff.js
It's propose only a window.diff() who takes two arrays and that's it.

So if you want to make a diff between two strings you can do:
``` javascript
result = diff(
    "first_string".split(""),
    "second_string".split("")
);
```
