### ISSUE TITLE
Meta: The QUnit 2.0 plan

### ISSUE THREAD

**Issue by leobalter** [jquery/qunit#891]
QUnit 2.0 is close, and we only have some a few issues to solve until it's done. This is a meta issue with the agenda for the new QUnit 2.0:

- [ ] #422 EventEmitter - PR at #882
- [x] #890 QUnit.reporter method with built-in tap
- [ ] #881 Throw warnings for deprecated messages
- [x] Release the last QUnit 1.x before QUnit 2 (no new features until QUnit 2)
- \o/
- [x] Remove the warnings for deprecated methods
- [x] Apply the breaking changes with warnings (see https://github.com/jquery/qunit/milestones/v2.0)
- [x] Release QUnit 2.0 / drops support for ES3 / change support to ES5+
- \o/
- [ ] Remove the warnings for methods removed in QUnit 2.0
- [ ] Release QUnit 2.1
- [ ] QUnit.reporter(require('qunit-reporter-html'))
- [ ] QUnit replaces built-in tap reporter with js-reporters/tap

Any other features are not blockers for this process, so we can still have features like `QUnit.pending` and `_.deepEqual` before QUnit 2 or #881.

**Comment by leobalter** [comment]
#890 was dropped.

**Comment by platinumazure** [comment]
Wondering how accurate this still is as a representation of things that need to be done before QUnit 2.0. And if this is still accurate, are there people on all of these, or do some of these items potentially need volunteers?

**Comment by leobalter** [comment]
Good point. This turned as a bit inaccurate, but the central idea just happened.

Some features will make their way now with 2.0 released.

I'm closing this as this is now leading to more misunderstanding than anything else.

**Comment by trentmwillis** [comment]
@leobalter looks like you might be prepping the 2.1 release. Just wanting to make sure "Remove the warnings for methods removed in QUnit 2.0" is done.

**Comment by leobalter** [comment]
I missed that part. My bad. I'll do it as soon as I figure out how to solve the phantomjs thing.
